version: '3'

services:
  python3:
    build: ./python3
    command: uwsgi --socket :8001 --module project.wsgi --py-autoreload 1 --logto /tmp/app.log
    volumes:
      - ./src:/src
      - ./src/static:/src/static
    expose:
      - "8001"
    depends_on:
      - db

  db:
    build: postgresql
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    hostname: postgres
    restart: always
    user: root

  nginx:
    build: ./nginx
    ports:
      - "80:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/src/static
    depends_on:
      - python3

  dbadmin:
    image: dpage/pgadmin4:4
    ports:
      - ${PGADMIN_PORT}:8888
    volumes:
      - ./admin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    hostname: pgadmin4
    restart: always
